<header class="container">
    <div class="content">
        <h1 class="main_logo text-center">
        <i class="fa fa-3x fa-ship"></i></br>
        <label style="font-family: 'Indie Flower', cursive;">PLUTON</label>
        </h1>
    </div>
</header>
<div class="container container-fluidr center-block">
    <div class="content modal-content">
        <article class="content">
        <h1 class="hidden">Config.ini</h1>
        <p> Exemplo de arquivo de configuração:</p>
        <article class="text-primary content col-sm-offset-1">
        <textarea readonly cols="50" rows="7" style="resize: none;">
            [database]
            adapter  = Mysql
            host     = localhost
            username = root
            password =
            name     = pluton
        </textarea>
        </article>
        <p> Caso ocorra algum erro durante a configuração, copie o conteúdo acima modificando os dados pelos do seu servidor de banco e cole no arquivo apps/config/config.ini. Crie este arquivo caso ele não exista. </p>
        </article>
    </div>
    <div class="clearfix"></div>
</div>
