<style>
    body { background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABoAAAAaCAYAAACpSkzOAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAABZ0RVh0Q3JlYXRpb24gVGltZQAxMC8yOS8xMiKqq3kAAAAcdEVYdFNvZnR3YXJlAEFkb2JlIEZpcmV3b3JrcyBDUzVxteM2AAABHklEQVRIib2Vyw6EIAxFW5idr///Qx9sfG3pLEyJ3tAwi5EmBqRo7vHawiEEERHS6x7MTMxMVv6+z3tPMUYSkfTM/R0fEaG2bbMv+Gc4nZzn+dN4HAcREa3r+hi3bcuu68jLskhVIlW073tWaYlQ9+F9IpqmSfq+fwskhdO/AwmUTJXrOuaRQNeRkOd5lq7rXmS5InmERKoER/QMvUAPlZDHcZRhGN4CSeGY+aHMqgcks5RrHv/eeh455x5KrMq2yHQdibDO6ncG/KZWL7M8xDyS1/MIO0NJqdULLS81X6/X6aR0nqBSJcPeZnlZrzN477NKURn2Nus8sjzmEII0TfMiyxUuxphVWjpJkbx0btUnshRihVv70Bv8ItXq6Asoi/ZiCbU6YgAAAABJRU5ErkJggg==);}
    .page-header{
        margin-top: -19px !important;
    }
    footer{
        margin-left: 14%;
    }
</style>
<!-- Navigation -->
<div>
    <?= $this->partial("index/navBar") ?>
</div>
<?= $this->getContent(); ?>
<footer class="navbar-fixed-bottom">
    <div class="row">
        <?= $this->partial("index/footer") ?>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
</footer>

<script>
var Raptor = function(){
    /**
    * Seta a classe para os campos editaveis e inicia o plugin
    */
    this.init = function(){
        //Adiciona a classe 'raptor-editable aos itens que podem ser editados pelo usuário'
        $("#home, #about, #contact, .page-header, #navigation").addClass('raptor-editable');
        $("#blog-search, #side-widget, #footer").addClass('raptor-editable');
        $("top-navbar").css('margin-top', '150px !important');
        $('.raptor-editable').raptor({
            plugins: {
                save: {
                    plugin: 'saveRest'
                },
                saveRest: {
                    url: 'appearance/save',
                    data: function(html) {
                        return {
                            id: this.raptor.getElement().data('id'),
                            content: html
                        };
                    }
                },
                dock: {
                    docked: false
                }
            }
        });
    }
}

var editor = ('<?= $edit_appearance ?>');
if(editor){
    raptor = new Raptor;
    raptor.init();
}
</script>