<div class="panel-heading">
    <i class="glyphicon glyphicon-stats"></i> Acessos
</div>
<!-- /.panel-heading -->
<div class="panel-body">
    <div>
        <canvas id="canvas" height="250" width="400"></canvas>
        <small>Dados retirados de <a href="http://www.google.com/analytics/">Google Analytics</a></small>
    </div>
</div>
<!-- /.panel-body -->
<script>
        var lineChartData = {
            labels: <?= json_encode($months) ?>,
            datasets: [
                {
                    label: "Acessos",
                    fillColor: "rgba(220,220,220,0.2)",
                    strokeColor: "rgba(220,220,220,1)",
                    pointColor: "rgba(220,220,220,1)",
                    pointStrokeColor: "#fff",
                    pointHighlightFill: "#fff",
                    pointHighlightStroke: "rgba(220,220,220,1)",
                    data: <?= json_encode($sessions) ?>
                }
            ]
        }
        window.onload = function () {
            var ctx = document.getElementById("canvas").getContext("2d");
            window.myLine = new Chart(ctx).Line(lineChartData, {
                responsive: true
            });
        }
</script>