<div class="list-group panel">
<?php foreach($menus as $menu){  ?>
    <?php if($menu['level_permission'] <= $user_type_id){ ?>
        <a href="<?php if(!empty($menu['submenu'])){
                    echo $menu['menu_href'];
                } else{
                    echo URL_PROJECT . $menu['menu_href'];
                } ?>"

        class="list-group-item strong" <?php if(!empty($menu['submenu'])) echo "data-parent='#MainMenu' data-toggle='collapse'"?>>
            <i class="<?= $menu['menu_icon'] ?>"></i> <?= $menu['menu_name'] ?>
        </a>
        <?php if(!empty($menu['submenu'])) { ?>
            <!-- remover # do menu_href para exibir aqui -->
            <div class="collapse" id="<?= $menu['submenu_div_name'] ?>">
                <?php foreach($menu['submenu'] as $submenu){ //var_dump($submenu); die();?>
                    <a href="<?= URL_PROJECT . $submenu['submenu_href'] ?>" class="list-group-item"><i class="<?= $submenu['submenu_icon'] ?>"></i> <?= $submenu['submenu_name'] ?></a>
                <?php } ?>
            </div>
        <?php } ?>
    <?php } ?>
<?php } ?>
</div>