<div class="panel panel-default" >
    <div class="panel-heading">
        <?php if(!empty($plugin['plugin_id'])){ ?>
            <label style="font-size: 30px;"><i class="glyphicon glyphicon-edit"></i> Editar Plugin</label>
        <?php } else{?>
            <label style="font-size: 30px;"><i class="glyphicon glyphicon-plus"></i> Novo Plugin</label>
        <?php } ?>
    </div>
    <div class="panel-body">
        <div class="col-sm-8">
            <div class="row">
                <form id="plugin" name="plugin" role="form">
                    <input type="hidden" name="menu_id" value="<?= $menu['menu_id'] ?>">
                    <input type="hidden" name="submenu1_id" value="<?= $submenu1['submenu_id'] ?>">
                    <input type="hidden" name="submenu2_id" value="<?= $submenu2['submenu_id'] ?>">
                    <div class="form-group col-sm-10">
                        <input type="text" name="plugin_name" class="form-control" value="<?= $plugin['plugin_name']?>" placeholder="Nome do Plugin">
                    </div>
                    <div class="form-group col-sm-10">
                        <input type="text" name="exibition_name" value="<?= $menu['menu_name'] ?>" class="form-control" placeholder="Nome de Exibição">
                    </div>
                    <div class="form-group col-sm-10">
                        <input type="text" name="icon" class="form-control" value="<?= $menu['menu_icon'] ?>" placeholder="Ícone de exibição">
                    </div>
                    <div class="form-group col-sm-10">
                        <input type="text" name="url" class="form-control" value="<?= $menu['menu_href'] ?>" placeholder="URL ou controller/action">
                    </div>
                    <div class="form-group col-sm-10">
                        <select name="level_permission" id="level_permission" class="form-control">
                            <option value="">Nível de Permissão</option>
                            <option value="1"> 1 - Somente Super Administrador</option>
                            <option value="2"> 2 - Super Administrador e Administrador</option>
                            <option value="3"> 3 - Super Administrador, Administrador e Editor</option>
                            <option value="4"> 4 - Super Administrador, Administrador, Editor e Autor</option>
                            <option value="5"> 5 - Super Administrador, Administrador, Editor, Autor e colaborador</option>
                        </select>
                    </div>
                    <div class="form-group col-sm-10">
                        <label>** Se não deseja inserir submenus, deixe as opções abaixo em branco</label>
                    </div>
                    <div class="form-group col-sm-10">
                        <label>Submenu 1</label>
                    </div>
                    <div class="form-group col-sm-10">
                        <input type="text" name="submenu1_name" value="<?= $submenu1['submenu_name']?>" class="form-control" placeholder="Nome de Exibição do submenu">
                    </div>
                    <div class="form-group col-sm-10">
                        <input type="text" name="submenu1_url" class="form-control" value="<?= $submenu1['submenu_href']?>" placeholder="URL ou controller/action">
                    </div>
                    <div class="form-group col-sm-10">
                        <input type="text" name="submenu1_icon" class="form-control" value="<?= $submenu1['submenu_icon']?>" placeholder="Ícone de exibição">
                    </div>
                    <div class="form-group col-sm-10">
                        <label>Submenu 2</label>
                    </div>
                     <div class="form-group col-sm-10">
                        <input type="text" name="submenu2_name" value="<?= $submenu2['submenu_name']?>" class="form-control" placeholder="Nome de Exibição do submenu">
                    </div>
                    <div class="form-group col-sm-10">
                        <input type="text" name="submenu2_url" class="form-control" value="<?= $submenu2['submenu_href']?>" placeholder="URL ou controller/action">
                    </div>
                    <div class="form-group col-sm-10">
                        <input type="text" name="submenu2_icon" class="form-control" value="<?= $submenu2['submenu_icon']?>" placeholder="Ícone de exibição">
                    </div>

                    <div class="form-group col-sm-6">
                        <?php if(empty($plugin['plugin_id'])){ ?>
                        <a href="#" id="save-plugin" class="btn btn-block btn-primary btn-success"><span class="glyphicon glyphicon-ok"></span> Adicionar</a>
                        <?php } else{ ?>
                        <a href="#" id="edit-plugin" class="btn btn-block btn-primary btn-warning"><span class="glyphicon glyphicon-edit"></span> Salvar Alterações</a>
                        <?php }?>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="panel panel-warning">
                <div class="panel-heading">
                    Atenção!
                </div>
                <div class="panel-body">
                </div>
                <div class="panel-footer">
                </div>
            </div>
        </div>
    </div>
</div>

<script>

$("#level_permission").val(<?= $menu['menu_level_permission']?>);

$("#save-plugin").click(function(){
    var form = $("#plugin").serialize();
    $.ajax({
        url: "<?= URL_PROJECT ?>plugin/addPlugin",
        data: form,
        dataType: 'json',
        type: "POST",
        success: function(data){
            if(data.success){
                swal({
                    title: "Sucesso!",
                    text: "Dados Salvos Com sucesso! ",
                    type: "success",
                    confirmButtonText: "OK"
                });
            } else{
                swal({
                    title: "Erro!",
                    text: "Por favor, verifique os dados Informados e tente Novamente!",
                    type: "error",
                    confirmButtonText: "OK"
                });
            }
        }
    });
});

$("#edit-plugin").click(function(){
    var form = $("#plugin").serialize();
    $.ajax({
        url: "<?= URL_PROJECT ?>plugin/updatePlugin",
        data: form,
        dataType: 'json',
        type: "POST",
        success: function(data){
            if(data.success){
                swal({
                    title: "Sucesso!",
                    text: "Dados Salvos Com sucesso! ",
                    type: "success",
                    confirmButtonText: "OK"
                });
            } else{
                swal({
                    title: "Erro!",
                    text: "Por favor, verifique os dados Informados e tente Novamente!",
                    type: "error",
                    confirmButtonText: "OK"
                });
            }
        }
    });
});
</script>
