<div class="panel panel-default" >
    <div class="panel-heading">
        <label style="font-size: 30px;"><i class="glyphicon glyphicon-plus"></i> Novo Plugin</label>
    </div>
    <div class="panel-body">
        <div class="col-sm-8">
            <div class="row">
                <form id="plugin" name="plugin" role="form">
                    <div class="form-group col-sm-10">
                        <input type="text" name="plugin_name" class="form-control" value="" placeholder="Nome do Plugin">
                    </div>
                    <div class="form-group col-sm-10">
                        <input type="text" name="exibition_name" value="" class="form-control" placeholder="Nome de Exibição">
                    </div>
                    <div class="form-group col-sm-10">
                        <input type="text" name="icon" class="form-control" value="" placeholder="Ícone de exibição">
                    </div>
                    <div class="form-group col-sm-10">
                        <input type="text" name="url" class="form-control" value="" placeholder="URL ou controller/action">
                    </div>
                    <div class="form-group col-sm-10">
                        <select name="level_permission" class="form-control">
                            <option value="">Nível de Permissão</option>
                            <option value="1"> Somente Super Administrador</option>
                            <option value="2"> Super Administrador e Administrador</option>
                            <option value="3"> Super Administrador, Administrador e Editor</option>
                            <option value="4"> Super Administrador, Administrador, Editor e Autor</option>
                            <option value="5"> Super Administrador, Administrador, Editor, Autor e colaborador</option>
                        </select>
                    </div>
                    <div class="form-group col-sm-10">
                        <label>** Se não deseja inserir submenus, deixe as opções abaixo em branco</label>
                    </div>
                    <div class="form-group col-sm-10">
                        <label>Submenu 1</label>
                    </div>
                    <div class="form-group col-sm-10">
                        <input type="text" name="submenu1_name" value="" class="form-control" placeholder="Nome de Exibição do submenu">
                    </div>
                    <div class="form-group col-sm-10">
                        <input type="text" name="submenu1_url" class="form-control" value="" placeholder="URL ou controller/action">
                    </div>
                    <div class="form-group col-sm-10">
                        <input type="text" name="submenu1_icon" class="form-control" value="" placeholder="Ícone de exibição">
                    </div>
                    <div class="form-group col-sm-10">
                        <label>Submenu 2</label>
                    </div>
                     <div class="form-group col-sm-10">
                        <input type="text" name="submenu2_name" value="" class="form-control" placeholder="Nome de Exibição do submenu">
                    </div>
                    <div class="form-group col-sm-10">
                        <input type="text" name="submenu2_url" class="form-control" value="" placeholder="URL ou controller/action">
                    </div>
                    <div class="form-group col-sm-10">
                        <input type="text" name="submenu2_icon" class="form-control" value="" placeholder="Ícone de exibição">
                    </div>

                    <div class="form-group col-sm-6">
                        <?php if(empty($plugin_id)){ ?>
                        <a href="#" id="save-plugin" class="btn btn-block btn-primary btn-success"><span class="glyphicon glyphicon-ok"></span> Adicionar</a>
                        <?php } else{ ?>
                        <a href="#" id="edit-plugin" class="btn btn-block btn-primary btn-warning"><span class="glyphicon glyphicon-edit"></span> Salvar Alterações</a>
                        <?php }?>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="panel panel-warning">
                <div class="panel-heading">
                    Atenção!
                </div>
                <div class="panel-body">
                </div>
                <div class="panel-footer">
                </div>
            </div>
        </div>
    </div>
</div>

<script>
$("#save-plugin").click(function(){
    var form = $("#plugin").serialize();
    $.ajax({
        url: "<?= URL_PROJECT ?>plugin/addPlugin",
        data: form,
        dataType: 'json',
        type: "POST",
        success: function(data){
            if(data.success){
                swal({
                    title: "Sucesso!",
                    text: "Dados Salvos Com sucesso! ",
                    type: "success",
                    confirmButtonText: "OK"
                });
            } else{
                swal({
                    title: "Erro!",
                    text: "Por favor, verifique os dados Informados e tente Novamente!",
                    type: "error",
                    confirmButtonText: "OK"
                });
            }
        }
    });
});

$("#edit-plugin").click(function(){
    var form = $("#plugin").serialize();
    $.ajax({
        url: "<?= URL_PROJECT ?>plugin/updatePlugin",
        data: form,
        dataType: 'json',
        type: "POST",
        success: function(data){
            if(data.success){
                swal({
                    title: "Sucesso!",
                    text: "Dados Salvos Com sucesso! ",
                    type: "success",
                    confirmButtonText: "OK"
                });
            } else{
                swal({
                    title: "Erro!",
                    text: "Por favor, verifique os dados Informados e tente Novamente!",
                    type: "error",
                    confirmButtonText: "OK"
                });
            }
        }
    });
});
</script>
