<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Posts</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Lista de posts
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Título</th>
                                <th>Autor</th>
                                <th>Categorias</th>
                                <th>Data</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($posts as $post){ ?>
                                <tr>
                                    <td><?= $post->post_id ?></td>
                                    <td><?= $post->post_title ?></td>
                                    <td><?= $post->author->user_name ?></td>
                                    <td><?= $categories[$post->post_id] ?></td>
                                    <td><?= $post->post_date_create ?></td>
                                    <td><?= $post->post_status->post_status_name ?></td>
                                </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->

    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
</div>
<!-- /#page-wrapper -->