<div class="tab-pane fade" id="facebook">
    <div class="col-sm-8">
        <div class="row">
            <form id="facebook-account" name="facebook-account" role="form">
                <div class="panel-heading">
                    <label style="font-size: 18px;"> Adicionar Link da Página</label>
                    </div>
                    <div class="form-group input-group col-sm-10">
                        <span class="input-group-addon">facebook.com/</span>
                        <input type="text" name="page_name" class="form-control" value="<?= $fb_page_name ?>" placeholder="exemplo">
                    </div>
                    <div class="form-group input-group col-sm-6">
                        <?php if(empty($fb_page_name)){ ?>
                            <a href="#" id="save-facebook-account" class="btn btn-block btn-primary btn-success"><span class="glyphicon glyphicon-ok"></span> Salvar</a>
                        <?php } else{ ?>
                            <a href="#" id="edit-facebook-account" class="btn btn-block btn-primary btn-warning"><span class="glyphicon glyphicon-edit"></span> Alterar</a>
                    <?php }?>
                </div>
            </form>
        </div>
        </div>
    <div class="col-lg-4">
        <div class="panel panel-warning">
            <div class="panel-heading">
                Atenção!
            </div>
            <div class="panel-body">

            </div>
            <div class="panel-footer">

            </div>
        </div>
    </div>
</div>


<script>
$("#save-facebook-account").click(function(){
    var form = $("#facebook-account").serialize();
    $.ajax({
        url: "<?= URL_PROJECT ?>settings/registerFacebookPageName",
        data: form,
        dataType: 'json',
        type: "POST",
        success: function(data){
            if(data.success){
                swal({
                    title: "Sucesso!",
                    text: "Dados Salvos Com sucesso! ",
                    type: "success",
                    confirmButtonText: "OK"
                });
            } else{
                swal({
                    title: "Erro!",
                    text: "Por favor, verifique os dados Informados e tente Novamente!",
                    type: "error",
                    confirmButtonText: "OK"
                });
            }
        }
    });
});

$("#edit-facebook-account").click(function(){
    var form = $("#facebook-account").serialize();
    $.ajax({
        url: "<?= URL_PROJECT ?>settings/updateFacebookPageName",
        data: form,
        dataType: 'json',
        type: "POST",
        success: function(data){
            if(data.success){
                swal({
                    title: "Sucesso!",
                    text: "Dados Salvos Com sucesso! ",
                    type: "success",
                    confirmButtonText: "OK"
                });
            } else{
                swal({
                    title: "Erro!",
                    text: "Por favor, verifique os dados Informados e tente Novamente!",
                    type: "error",
                    confirmButtonText: "OK"
                });
            }
        }
    });
});
</script>