<div class="col-lg-4" >
    <hr>
    <div >
        <!-- /.panel-heading -->
        <div class="panel-body">
            <div class="list-group">
                <div class="panel panel-warning">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-xs-3">
                                <i class="fa fa-3x fa-exchange"></i>
                            </div>
                            <div class="col-xs-9 text-right">
                                <div class="huge"><?= $total_sessions?></div>
                                <div>Acessos Únicos</div>
                            </div>
                        </div>
                    </div>
                    <!--<a href="#">
                        <div class="panel-footer">
                            <span class="pull-left">Ver Mais</span>
                            <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                            <div class="clearfix"></div>
                        </div>
                    </a>-->
                </div>
            </div>
            <div class="panel panel-green">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="glyphicon glyphicon-large glyphicon-tags"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge"><?= $total_posts ?></div>
                            <div>Posts Publicados</div>
                        </div>
                    </div>
                </div>
                <!--<a href="#">
                    <div class="panel-footer">
                        <span class="pull-left">Ver Mais</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    </div>
                </a>-->
            </div>

            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-4x fa-facebook"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge"><?= $facebook_likes ?></div>
                            <div>Curtidas</div>
                        </div>
                    </div>
                </div>
                <!--<a href="#">
                    <div class="panel-footer">
                        <span class="pull-left">Ver Mais</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    </div>
                </a>-->
            </div>
            <div class="panel panel-info">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-4x fa-twitter"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge"><?= $followers_count ?></div>
                            <div>Seguidores</div>
                        </div>
                    </div>
                </div>
                <!--<a href="#">
                    <div class="panel-footer">
                        <span class="pull-left">Ver Mais</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    </div>
                </a>-->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
</div>
<!-- /.col-lg-4 -->