<style>
.timeline-body {
  overflow: hidden;
  text-overflow: ellipsis;
  max-height: 300px;
}

.timeline-body p img{
    display: none;
}
.timeline-body div img{
    display: none;
}
</style>

<div class="panel panel-default" id="lastPosts">
    <div class="panel-heading">
        <i class="glyphicon glyphicon-list"></i> Últimas postagens
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
        <ul class="timeline">
            <?php $side = 0;
            foreach($posts as $post){ ?>

                <li <?= $side%2 != 0 ? 'class=timeline-inverted' : ''?> >
                    <div class="timeline-badge">
                         <?php $img_profile = ($post->author->user_img == NULL) ? URL_PROJECT . "img/defaultProfile.png" : URL_PROJECT . "img/users/" . $post->author->user_img ?>
                            <img title="<?= $post->author->user_name ?>" width="100%" class="img-circle" src="<?= $img_profile; ?>">
                    </div>
                    <div class="timeline-panel">
                        <div class="timeline-heading">
                            <h4 class="timeline-title"><?= $post->post_title ?></h4>
                            <?php $date_posted = new DateTime($post->post_date_create); ?>
                            <p><small class="text-muted"><i class="glyphicon glyphicon-calendar"></i> Criado <?= $date_posted->format('d/m/Y - H:i:s')?></small>
                            </p>
                        </div>
                        <div class="timeline-body">
                            <p><?= html_entity_decode($post_content[$post->post_id]) ?></p>
                        </div>
                    </div>
                </li>

            <?php $side++;
            } ?>
        </ul>
        <!-- timeline -->
    </div>
    <!-- /.panel-body -->
</div>
<!-- /.panel -->

<script>
$("#").click(function(){

});
</script>