<div class="tab-pane fade in active" id="preferences">
    <div class="col-sm-8">
        <div class="row">
            <form id="preferences-form" name="preferences-form" role="form">
                <div class="panel-heading">
                    <label style="font-size: 18px;"> Preferências</label>
                </div>
                <div class="form-group input-group col-sm-10">
                    <span class="input-group-addon">Título Blog</span>
                    <input type="text" name="title_blog" class="form-control" value="<?= $title ?>" placeholder="TÍTULO DO BLOG">
                </div>
                <div class="form-group input-group col-sm-10">
                    <span class="input-group-addon"><i class="fa fa-link"></i></span>
                    <input type="text" name="url_project" class="form-control" value="<?= $url ?>" placeholder="URL">
                </div>
                <div class="form-group input-group col-offset-2">
                    <label>Envio de E-mails: </label><input type="checkbox" name="send_mail" class="mail-checkbox" checked>
                </div>
                <div class="form-group input-group col-sm-10">

                        <span class="input-group-addon"><i class="fa fa-google"></i> <i class="fa fa-envelope"></i></span>
                        <input type="email" name="mail_project" class="form-control" value="<?= $mail ?>" placeholder="exemplo@gmail.com">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-asterisk"></i></span>
                        <input type="password" name="mail_password" class="form-control" value="" placeholder="Senha da conta de email">
                </div>
                <div class="form-group input-group col-offset-2">
                    <span><label style="color: #0066CC;">Este email é utilizado para fins administrativos. (Somente conta google)</label></span>
                </div>
                <div class="form-group input-group col-offset-2">
                    <label>Sobre o Blog:</label>

                    <textarea name="post_content" id="inputPost_content" class="form-control" rows="3" required="required"></textarea>
                </div>
                <div class="form-group input-group col-sm-10">
                    <a href="#" id="edit-preferences" class="col-sm-5 btn btn-primary btn-warning"><span class="glyphicon glyphicon-edit"></span> Salvar Informações</a>
                    <?php if($user_type_id == 1){ ?>
                    <a href="#" class="btn btn-primary btn-info" style="float:right;" id="theme-editor"><span class="glyphicon glyphicon-new-window"></span> Editar Aparência do Blog</a>
                    <?php } ?>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
$("#theme-editor").click(function(){
    window.open("<?= URL_PROJECT ?>appearance/index");
});
$("#edit-preferences").click(function(){
    var form = $("#preferences-form").serialize();
    $.ajax({
        url: "<?= URL_PROJECT ?>settings/updatePreferences",
        data: form + '&blog_about=' + tinyMCE.activeEditor.getContent(),
        dataType: 'json',
        type: "POST",
        success: function(data){
            if(data.success){
                swal({
                    title: "Sucesso!",
                    text: "Dados Salvos Com sucesso! ",
                    type: "success",
                    confirmButtonText: "OK"
                });
            } else{
                swal({
                    title: "Erro!",
                    text: "Por favor, verifique os dados Informados e tente Novamente!",
                    type: "error",
                    confirmButtonText: "OK"
                });
            }
        }
    });
});

$(".mail-checkbox").bootstrapSwitch({
    state: <?= $mail_active ?>,
    size: "small",
    offColor: "warning"
});

/**
 * Carrega o editor wysiwyg tinymce para edição de uma nova postagem
 */
tinymce.init({
    selector: "#inputPost_content",
    theme: "modern",
    height : 300,
    width: 600,
    init_instance_callback: "insert_contents",
    plugins: [
        "advlist autolink lists link image charmap print preview hr anchor pagebreak",
        "searchreplace wordcount visualblocks visualchars code fullscreen",
        "insertdatetime media nonbreaking save table contextmenu directionality",
        "emoticons template paste textcolor colorpicker textpattern imagetools"
    ],
    toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
    toolbar2: "print preview media | forecolor backcolor emoticons",
    image_advtab: true,
    templates: [
        {title: 'Test template 1', content: 'Test 1'},
        {title: 'Test template 2', content: 'Test 2'}
    ],
    entity_encoding : "raw",
    title: 'post_content',
    language: 'pt_BR'

});

function insert_contents(inst){
    inst.setContent('<?= $blog_about ?>');
}
</script>