<div class="list-group panel">
    <?php if($user_type_id == 1 || $user_type_id == 2){ ?>
    <a href="#sub-users" class="list-group-item strong" data-toggle="collapse" data-parent="#MainMenu"><i class="glyphicon glyphicon-user"></i> Usuários</a>
    <div class="collapse" id="sub-users">
        <a href="#" class="list-group-item" id="new-user"><i class="glyphicon glyphicon-plus"></i> Novo</a>
        <a href="#" class="list-group-item" id="edit-user"><i class="glyphicon glyphicon-edit"></i> Editar</a>
    </div>
    <!-- /sub-users-->
    <?php } ?>
    <a href="#sub-posts" class="list-group-item strong" data-toggle="collapse" data-parent="#MainMenu"><i class="glyphicon glyphicon-tags"></i> Posts </a>
    <div class="collapse" id="sub-posts">
        <a href="#" class="list-group-item" id="new-post"><i class="glyphicon glyphicon-plus"></i> Novo</a>
        <a href="#" class="list-group-item" id="edit-post"><i class="glyphicon glyphicon-edit"></i> Editar</a>
    </div>
    <!-- /sub-posts -->
    <?php if($user_type_id == 1 | $user_type_id == 2){ ?>
    <?php } ?>
    <?php if($user_type_id == 1){ ?>
    <a href="#sub-appearance" class="list-group-item strong" data-toggle="collapse" data-parent="#MainMenu"><i class="glyphicon glyphicon-sunglasses"></i> Aparência </a>
    <div class="collapse" id="sub-appearance">
        <a href="#" class="list-group-item" id="theme-editor"><i class="glyphicon glyphicon-edit"></i> Editar Aparência</a>
    </div>
    <!-- /sub-appearance-->
    <?php } ?>
    <?php if($user_type_id == 1 || $user_type_id == 2){ ?>
    <a href="#" id="security" class="list-group-item strong" data-toggle="collapse" data-parent="#MainMenu"><i class="glyphicon glyphicon-eye-open"></i> APIS e Redes Sociais </a>
    <?php } ?>
    <?php if($user_type_id == 1){ ?>
    <a href="#" class="list-group-item strong" id="update" data-toggle="collapse" data-parent="#MainMenu"><i class="glyphicon     glyphicon-refresh"></i> Atualizações </a>
    <?php } ?>
</div>
<!-- /.list-group -->

<script type="text/javascript">

$("#new-user").click(function(){
    $.loadPartialView('main', '<?= URL_PROJECT ?>settings/newUser');
    $("#panel, #top-menu").attr("hidden", true);
});

$("#edit-user").click(function(){
    $.loadPartialView('main', '<?= URL_PROJECT?>settings/listUsers');
    $("#panel, #top-menu").attr("hidden", true);
});

$("#theme-editor").click(function(){
    window.open("<?= URL_PROJECT ?>appearance/index");

});

$("#new-post").click(function(){
    $.loadPartialView('main', '<?= URL_PROJECT?>post/index');
    $("#panel, #top-menu").attr("hidden", true);
});

$("#edit-post").click(function(){
    $.loadPartialView('main', '<?= URL_PROJECT?>post/listPosts');
    $("#panel, #top-menu").attr("hidden", true);
});

$("#security").click(function(){
    $.loadPartialView('main', '<?= URL_PROJECT?>security/index');
    $("#panel, #top-menu").attr("hidden", true);
});

$("#update").click(function(){
    $.loadPartialView('main', '<?= URL_PROJECT?>update/index');
    $("#panel, #top-menu").attr("hidden", true);
});
</script>