<div class="list-group panel">
    <?php if($user_type_id == 1){ ?>
    <a href="#sub-blog" class="list-group-item strong" id="blog" data-toggle="collapse" data-parent="#MainMenu"><i class="glyphicon glyphicon-home"></i> Blog</a>
    <?php } ?>
    <?php if($user_type_id == 1 || $user_type_id == 2){ ?>
    <a href="#sub-users" class="list-group-item strong" data-toggle="collapse" data-parent="#MainMenu"><i class="glyphicon glyphicon-user"></i> Usuários</a>
    <div class="collapse" id="sub-users">
        <a href="#" class="list-group-item" id="new-user"><i class="glyphicon glyphicon-plus"></i> Novo</a>
        <a href="#" class="list-group-item" id="edit-user"><i class="glyphicon glyphicon-edit"></i> Editar</a>
    </div>
    <!-- /sub-users-->
    <?php } ?>
    <a href="#sub-posts" class="list-group-item strong" data-toggle="collapse" data-parent="#MainMenu"><i class="glyphicon glyphicon-tags"></i> Posts </a>
    <div class="collapse" id="sub-posts">
        <a href="#" class="list-group-item" id="new-post"><i class="glyphicon glyphicon-plus"></i> Novo</a>
        <a href="#" class="list-group-item" id="edit-post"><i class="glyphicon glyphicon-edit"></i> Editar</a>
    </div>
    <!-- /sub-posts -->
    <?php if($user_type_id == 1 | $user_type_id == 2){ ?>
    <a href="#sub-analytics" class="list-group-item strong" data-toggle="collapse" data-parent="#MainMenu"><i class="glyphicon glyphicon-wrench"></i> Google Analytics </a>
    <div class="collapse" id="sub-analytics">
        <a href="#" class="list-group-item" id="g-account"><i class="glyphicon glyphicon-edit"></i> Cadastrar/Editar Conta</a>
        <a href="#" class="list-group-item" id="edit-post"><i class="glyphicon glyphicon-stats"></i> Relatórios</a>
    </div>
    <?php } ?>
    <?php if($user_type_id == 1 | $user_type_id == 2){ ?>
    <a href="#sub-social-network" class="list-group-item strong" data-toggle="collapse" data-parent="#MainMenu"><i class="glyphicon glyphicon-thumbs-up"></i> Redes Sociais </a>
    <div class="collapse" id="sub-social-network">
        <a href="#" class="list-group-item"><i class="glyphicon glyphicon-plus"></i> Adicionar Rede Social</a>
        <a href="#" class="list-group-item"><i class="glyphicon glyphicon-edit"></i> Editar Redes Cadastradas</a>
    </div>
    <!-- /sub-social-network -->
    <?php } ?>
    <?php if($user_type_id == 1 | $user_type_id == 2){ ?>
    <a href="#" class="list-group-item strong" data-toggle="collapse" data-parent="#MainMenu"><i class="glyphicon glyphicon-usd"></i> Propagandas </a>
    <?php } ?>
    <?php if($user_type_id == 1){ ?>
    <a href="#sub-appearance" class="list-group-item strong" data-toggle="collapse" data-parent="#MainMenu"><i class="glyphicon glyphicon-sunglasses"></i> Aparência </a>
    <div class="collapse" id="sub-appearance">
        <a href="#" class="list-group-item" id="theme-editor"><i class="glyphicon glyphicon-edit"></i> Editar Aparência</a>
    </div>
    <!-- /sub-appearance-->
    <?php } ?>
    <?php if($user_type_id == 1 || $user_type_id == 2){ ?>
    <a href="#" class="list-group-item strong" data-toggle="collapse" data-parent="#MainMenu"><i class="glyphicon glyphicon-eye-open"></i> Segurança </a>
    <?php } ?>
    <?php if($user_type_id == 'SA'){ ?>
    <a href="#sub-plugins" class="list-group-item strong" data-toggle="collapse" data-parent="#MainMenu"><i class="glyphicon glyphicon-paperclip"></i> Plugins </a>
    <div class="collapse" id="sub-plugins">
        <a href="#" class="list-group-item">Instalar Plugin</a>
        <a href="#" class="list-group-item">Buscar Plugins</a>
        <a href="#" class="list-group-item">Remover Plugin</a>
    </div>
    <!-- /sub-plugins -->
    <?php } ?>
    <?php if($user_type_id == 1){ ?>
    <a href="#sub-update" class="list-group-item strong" data-toggle="collapse" data-parent="#MainMenu"><i class="glyphicon     glyphicon-refresh"></i> Atualizações </a>
    <?php } ?>
</div>
<!-- /.list-group -->

<script type="text/javascript">

$("#new-user").click(function(){
    $.loadPartialView('main', '<?= URL_PROJECT ?>settings/newUser');
    $("#panel, #top-menu").attr("hidden", true);
});

$("#edit-user").click(function(){
    $.loadPartialView('main', '<?= URL_PROJECT?>settings/listUsers');
    $("#panel, #top-menu").attr("hidden", true);
});

$("#theme-editor").click(function(){
    window.open("<?= URL_PROJECT ?>appearance/index");

});

$("#new-post").click(function(){
    $.loadPartialView('main', '<?= URL_PROJECT?>post/index');
    $("#panel, #top-menu").attr("hidden", true);
});

$("#edit-post").click(function(){
    $.loadPartialView('main', '<?= URL_PROJECT?>post/listPosts');
    $("#panel, #top-menu").attr("hidden", true);
})

$("#g-account").click(function(){
    $.loadPartialView('main', '<?= URL_PROJECT?>analytics/index');
    $("#panel, #top-menu").attr("hidden", true);
})
</script>