<style>
    body { background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABoAAAAaCAYAAACpSkzOAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAABZ0RVh0Q3JlYXRpb24gVGltZQAxMC8yOS8xMiKqq3kAAAAcdEVYdFNvZnR3YXJlAEFkb2JlIEZpcmV3b3JrcyBDUzVxteM2AAABHklEQVRIib2Vyw6EIAxFW5idr///Qx9sfG3pLEyJ3tAwi5EmBqRo7vHawiEEERHS6x7MTMxMVv6+z3tPMUYSkfTM/R0fEaG2bbMv+Gc4nZzn+dN4HAcREa3r+hi3bcuu68jLskhVIlW073tWaYlQ9+F9IpqmSfq+fwskhdO/AwmUTJXrOuaRQNeRkOd5lq7rXmS5InmERKoER/QMvUAPlZDHcZRhGN4CSeGY+aHMqgcks5RrHv/eeh455x5KrMq2yHQdibDO6ncG/KZWL7M8xDyS1/MIO0NJqdULLS81X6/X6aR0nqBSJcPeZnlZrzN477NKURn2Nus8sjzmEII0TfMiyxUuxphVWjpJkbx0btUnshRihVv70Bv8ItXq6Asoi/ZiCbU6YgAAAABJRU5ErkJggg==);}
</style>
<!-- Navigation -->
<div>
    <nav id="top-navbar" class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#" data-id="title"><?= html_entity_decode($layout->layout_title) ?></a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" data-id="navbar" id="navbar">
                <?= html_entity_decode($layout->layout_navbar) ?>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
</div>
<!-- Page Content -->
<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8">
            <h1 class="page-header" data-id="subtitle">
            <?= html_entity_decode($layout->layout_subtitle) ?>
            </h1>
            <!-- First Blog Post -->
            <h2>
            <a href="#">Blog Post Title</a>
            </h2>
            <p class="lead">
            by <a href="index.php">Start Bootstrap</a>
            </p>
            <p><span class="glyphicon glyphicon-time"></span> Posted on August 28, 2013 at 10:00 PM</p>
            <hr>
            <img class="img-responsive" src="http://placehold.it/900x300" alt="">
            <hr>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore, veritatis, tempora, necessitatibus inventore nisi quam quia repellat ut tempore laborum possimus eum dicta id animi corrupti debitis ipsum officiis rerum.</p>
            <a class="btn btn-primary" href="#">Read More <span class="glyphicon glyphicon-chevron-right"></span></a>
            <hr>
            <hr>
            <!-- Pager -->
            <ul id="navigation" data-id="navigation" class="pager">
                <?= html_entity_decode($layout->layout_navigation) ?>
            </ul>
        </div>
        <!-- Blog Sidebar Widgets Column -->
        <div class="col-md-4">
            <!-- Blog Search Well -->
            <div id="blog-search" data-id="searchbar" class="well">
                <?= html_entity_decode($layout->layout_searchbar) ?>
            </div>
            <!-- Blog Categories Well -->
            <div class="well">
                <h4 id="title-categories">Blog Categories</h4>
                <div class="row">
                    <div class="col-lg-6">
                        <ul class="list-unstyled">
                            <li><a href="#">Category Name</a>
                            </li>
                            <li><a href="#">Category Name</a>
                            </li>
                            <li><a href="#">Category Name</a>
                            </li>
                            <li><a href="#">Category Name</a>
                            </li>
                        </ul>
                    </div>
                    <!-- /.col-lg-6 -->
                    <div class="col-lg-6">
                        <ul class="list-unstyled">
                            <li><a href="#">Category Name</a>
                            </li>
                            <li><a href="#">Category Name</a>
                            </li>
                            <li><a href="#">Category Name</a>
                            </li>
                            <li><a href="#">Category Name</a>
                            </li>
                        </ul>
                    </div>
                    <!-- /.col-lg-6 -->
                </div>
                <!-- /.row -->
            </div>
            <!-- Side Widget Well -->
            <div id="side-widget" data-id="lateralbar" class="well">
                <?= html_entity_decode($layout->layout_lateralbar) ?>
            </div>
        </div>
    </div>
    <!-- /.row -->
    <hr>
    <!-- Footer -->
    <footer>
        <div class="row footer">
            <div id="footer" data-id="footer" class="col-lg-12">
                <?= html_entity_decode($layout->layout_footer) ?>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </footer>
</div>
<!-- /.container -->
<script>

var Raptor = function(){

    /**
     * Seta a classe para os campos editaveis e inicia o plugin
     */
    this.init = function(){
        //Adiciona a classe 'raptor-editable aos itens que podem ser editados pelo usuário'
        $("#navbar, .page-header, #navigation").addClass('raptor-editable');
        $("#blog-search, #footer, #side-widget").addClass('raptor-editable');
        $("top-navbar").css('margin-top', '150px !important');
        $('.raptor-editable').raptor({
            plugins: {
                save: {
                    plugin: 'saveRest'
                },
                saveRest: {
                    url: 'appearance/save',
                    data: function(html) {
                        return {
                            id: this.raptor.getElement().data('id'),
                            content: html
                        };
                    }
                },
                dock: {
                    docked: false
                }
            }
        });
    }
}

var editor = ('<?= $_REQUEST["editor"] ?>');
var session = ('<?= $this->session->get(user_id);?>');


if(editor && session != ''){
    raptor = new Raptor;
    raptor.init();
}



</script>