
<!-- Page Content -->
<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div id="post" class="col-md-8">
            <?= $this->partial("index/posts") ?>
        </div>
        <!-- Blog Sidebar Widgets Column -->
        <div class="col-md-4">
            <?= $this->partial("index/lateralBar") ?>
        </div>
    </div>
    <!-- /.row -->
    <hr>
    <!-- Footer -->

</div>
<!-- /.container -->
