<style>
    #top-navbar{
        position: relative !important;
        margin-top: -70px !important;
    }
</style>
<div>
    <nav id="top-navbar" class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?= URL_PROJECT ?>" data-id="title"><?= html_entity_decode($blog_name) ?></a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" data-id="navbar" id="navbar">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="<?= URL_PROJECT ?>" data-id="home" id="home"><?= html_entity_decode($layout->layout_menu1) ?></a>
                    </li>
                    <li>
                        <a href="<?= URL_PROJECT ?>index/about" data-id="about" id="about"><?= html_entity_decode($layout->layout_menu2) ?></a>
                    </li>
                    <li>
                        <a href="<?= URL_PROJECT ?>index/contact" data-id="contact" id="contact"><?= html_entity_decode($layout->layout_menu3) ?></a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
</div>
<div class="page-header" data-id="subtitle">
<?= html_entity_decode($layout->layout_subtitle) ?>