<header class="container">
    <div class="content">
        <h1 class="main_logo text-center">
        <img width="30%" src="<?= URL_PROJECT ?>img/logo.png"/>
        </h1>
    </div>
</header>
<div class="container">
    <div class="content border">
        <form class="form-signin" action="" method="">
            <input type="text" class="form-control" placeholder="Usuário" required autofocus>
            <input type="password" class="form-control" placeholder="Senha" required>
            <input type="button" id="login" class="btn btn-lg btn-default btn-block" value="Entrar" />
        </form>
    </div>
</div>

<script>
$("#login").on("click", function(){
    efetuarLogin();
});

function efetuarLogin(user, passwd){
    $.ajax({
        url: '',
        data: '',
        type: 'POST',
        dataType: 'json',
        success: function(data){
            window.location('settings/index');
        }
    })
}
</script>