<header class="container">
    <div class="content">
        <h1 class="main_logo text-center">
            <img width="30%" src="<?= URL_PROJECT ?>img/logo.png"/>
        </h1>
    </div>
</header>


<div class="container container-fluidr center-block">
    <div class="content modal-content">
        <article class="content">
            <h1 class="h3 text-center">Informações do Banco de Dados</h1>
            <form class="form-horizontal center-block" id="user_create" name="user_create">
                <div class="form-group">
                    <label class="col-sm-4 control-label">Banco de Dados: </label>
                    <div class="col-sm-7">
                        <input type="text" class="form-control" name="database_name" id="database_name" class="database_name" value="pluton">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-4 control-label">Usuário: </label>
                    <div class="col-sm-7">
                        <input type="text" class="form-control" name="database_user" id="database_user" class="database_user" value="root">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-4 control-label">Senha: </label>
                    <div class="col-sm-7">
                        <input type="text" class="form-control" name="database_paswd" id="database_paswd" class="database_paswd">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-4 control-label">Servidor: </label>
                    <div class="col-sm-7">
                        <input type="text" class="form-control" name="database_server" id="database_server" class="database_server" value="localhost">
                    </div>
                </div>
                <div class="text-justify">
                    <p>Caso os dados preenchidos, estejam diferentes do banco de dados criado em seu servidor, modifique-os antes de continuar.</p>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-5">
                        <input type="submit" class="btn btn-lg btn-default" id="prosseguir" value="Prossseguir" />
                    </div>
                </div>
            </form>
        </article>
    </div>
    <div class="clearfix"></div>
</div>
<script>
    $("#prosseguir").click(function () {
        window.location.href = 'setup/ConfigFileCreate';
    });
</script>