<header class="container">
    <div class="content">
        <h1 class="main_logo text-center">
            <img width="30%" src="<?= URL_PROJECT ?>img/logo.png"/>
        </h1>
    </div>
</header>


<div class="container-fluidr">
    <div class="modal-content col-sm-5 text-center">
        <article class="content">
            <h1 class="hidden">Bem Vindo</h1>
            <p class="text-justify">Bem vindo ao Pluton, antes de prosseguir precisamos de algumas informações a respeito do banco de dados. É necessário ter conhecimento sobre os seguintes itens:</p>
        </article>
        <article class=" text-primary">
            <ul>
            <h1 class="hidden">Dados Necessários</h1>
                <li>Nome do Banco de Dados</li>
                <li>Nome de Usuário do Banco de Dados</li>
                <li>Senha do Banco de Dados</li>
                <li>Servidor do Banco de Dados</li>
            </ul>
            <div class="form-group">
                <div class="col-sm-offset-5">
                    <input type="submit" class="btn btn-lg btn-default" id="prosseguir" value="Prossseguir" />
                </div>
            </div>

        </article>
    </div>
    <div class="clearfix"></div>
</div>