<header class="container">
    <div class="content">
        <h1 class="main_logo text-center">
            <img width="30%" src="<?= URL_PROJECT ?>img/logo.png"/>
        </h1>
    </div>
</header>

<div class="container">
    <div class="content">
        <article>
            <h3 class="text-center">Informe os dados do Usuário</h3>
            <form class="form-horizontal" action="setup/userCreate" method="POST">
                <div class="form-group">
                    <label class="col-sm-2 control-label">Nome:</label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control col-sm-3" name="user_name">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">Usuário:</label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control col-sm-3" name="user_email">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">Senha:</label>
                    <div class="col-sm-6">
                        <input type="password" class="form-control col-sm-3" name="user_password">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-5">
                        <button type="button" class="btn btn-default" id="prosseguir" > Prosseguir</button>
                    </div>
                </div>
            </form>
        </article>
    </div>
</div>