<style>
    div > form{
        margin-left: 20px;
        margin-right: 20px;
        margin-bottom: 20px;
    }
</style>
<div class="col-lg-12">
    <hr>
    <hr>
    <div class="panel panel-default" >
        <div class="panel-heading">
            <label style="font-size: 30px;"><i class="glyphicon glyphicon-eye-open"></i> Configurar APIS</label>
        </div>
        <!-- /.panel-heading -->
        <div class="panel-body">
            <!-- Nav tabs -->
            <ul class="nav nav-tabs">
                <li><a class="active" href="#google" data-toggle="tab"><i class="fa fa-2x fa-google"></i> Google</a>
                </li>
                <li><a href="#twitter" data-toggle="tab"><i class="fa fa-2x fa-twitter"></i> Twitter</a>
                </li>
                <li><a href="#facebook" data-toggle="tab"><i class="fa fa-2x fa-facebook"></i> Facebook</a>
                </li>
            </li>
        </ul>
        <!-- /.panel-heading -->
        <div class="tab-content">
            <?= $this->partial("security/googleTab") ?>
            <?= $this->partial("security/twitterTab") ?>
            <?= $this->partial("security/facebookTab") ?>
        </div>
    </div>
    <!-- /.panel-default -->
</div>
<!-- /.col-lg-8 -->