<style>

    div > form{

        margin-left: 20px;
        margin-right: 20px;
        margin-bottom: 20px;
    }
</style>
<div class="col-lg-12">
    <hr>
    <hr>
    <div class="panel panel-default" >
        <div class="panel-heading">
            <label style="font-size: 30px;"><i class="glyphicon glyphicon-eye-open"></i> Segurança</label>
        </div>
        <!-- /.panel-heading -->
        <div class="panel-body">
            <div class="panel-heading">
                <label style="font-size: 16px;"> <i class="glyphicon glyphicon-edit"></i> Gerenciar Contas</label>
            </div>
            <hr>
            <div class="col-sm-4">
                <div class="row">
                    <form name="google-account" id="google-account" role="form">
                        <div class="panel-heading">
                            <label style="font-size: 18px;"> <i class="fa fa-google"></i> Google</label>
                        </div>
                        <div class="form-group input-group col-sm-10">
                            <span class="input-group-addon">@</span>
                            <input type="text" name="g_account" id="g_account" class="form-control" placeholder="example@gmail.com">
                        </div>
                        <div class="form-group input-group col-sm-10">
                            <span class="input-group-addon glyphicon glyphicon-asterisk"></span>
                            <input type="password" name="g_password" id="g_password" class="form-control">
                        </div>

                        <div class="form-group input-group col-sm-6">
                            <a href="#" id="save-google-account" class="btn btn-block btn-primary btn-success"><span class="glyphicon glyphicon-ok"></span> Salvar</a>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-sm-4">

                <div class="row">
                    <form name="facebook-account" role="form">
                        <div class="panel-heading">
                            <label style="font-size: 18px;"> <i class="fa fa-facebook"></i> Facebook</label>
                        </div>
                        <div class="form-group input-group col-sm-10">
                            <span class="input-group-addon">@</span>
                            <input type="text" name="facebook-account" class="form-control" placeholder="example@gmail.com">
                        </div>
                        <div class="form-group input-group col-sm-10">
                            <span class="input-group-addon glyphicon glyphicon-asterisk"></span>
                            <input type="password" name="facebook-account" class="form-control">
                        </div>

                        <div class="form-group input-group col-sm-6">
                            <a href="#" id="save-facebook-account" class="btn btn-block btn-primary btn-success"><span class="glyphicon glyphicon-ok"></span> Salvar</a>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-sm-4">

                <div class="row">
                    <form name="facebook-account" role="form">
                        <div class="panel-heading">
                            <label style="font-size: 18px;"> <i class="fa fa-twitter"></i> Twitter</label>
                        </div>
                        <div class="form-group input-group col-sm-10">
                            <span class="input-group-addon">@</span>
                            <input type="text" class="form-control" placeholder="example@gmail.com">
                        </div>
                        <div class="form-group input-group col-sm-10">
                            <span class="input-group-addon glyphicon glyphicon-asterisk"></span>
                            <input type="password" class="form-control">
                        </div>

                        <div class="form-group input-group col-sm-6">
                            <a href="#" id="save-facebook-account" class="btn btn-block btn-primary btn-success"><span class="glyphicon glyphicon-ok"></span> Salvar</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!--<div class="panel-body">
            <div class="panel-heading">
                <label> <i class="glyphicon glyphicon-edit"></i>Configurações de E-mail</label>
            </div>
            <div class="col-sm-12">
                <div class="row">
                    <form role="form">
                        <div class="form-group input-group">
                            <span class="input-group-addon">@</span>
                            <input type="text" class="form-control" placeholder="example@gmail.com">
                        </div>
                        <div class="form-group input-group">
                            <span class="input-group-addon glyphicon glyphicon-asterisk"></span>
                            <input type="password" class="form-control">
                        </div>
                        <div class="form-group input-group col-sm-12">
                            <a href="#" class="btn btn-block btn-primary btn-success"><span class="glyphicon glyphicon-ok"></span> Salvar</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!-- /.panel-body -->
    </div>
    <!-- /.panel-default -->
</div>
<!-- /.col-lg-8 -->

<script>
$("#save-google-account").click(function(){
    console.log("save-google-account: \n");

    $.ajax({
        url: '<?= URL_PROJECT ?>security/registerGoogleAccounts',
        data: $("#google-account").serialize(),
        dataType: 'JSON',
        type: 'POST',
        success: function(data){
            if(data.success){
                swal({
                    title: "Atenção!",
                    text: "Dados Salvos com sucesso!",
                    type: "success",
                    confirmButtonText: "OK"
                });
            } else{
                swal({
                    title: "Atenção!",
                    text: "Ocorreu um problema ao inserir uma nova categoria. Por favor tente novamente!",
                    type: "error",
                    confirmButtonText: "OK"
                });
            }
        }
    })
});
</script>